baseURL = 'https://2029sheepyang.github.io/nienie/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'ananke'
publishDir = "docs"
canonifyurls = true
hasCJKLanguage = true
summaryLength = 30
[markup]
defaultMarkdownHandler = "goldmark"
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true